name: "Garrett Richard Ferrara"
tagline: "Intelligence Production • Narrative Risk • OSINT Methods"
email: ""          # TODO: Add your email address
linkedin: ""       # TODO: Add your full LinkedIn profile URL
github: "https://github.com/garrett-ferrara"
location: "Orlando, FL"
disclaimer: "Most of my professional work was completed while cleared or under NDA. The materials featured here are publicly shareable selections and academic projects."
about_short: >
  Analyst and editor integrating writing theory, intelligence tradecraft, and knowledge management to move the right information to the right hands at the right time.
